### ISSUE TITLE
Compendiums that still contain documents that have not been updated to `system` prevent the pages from rendering

### ISSUE THREAD

**Issue by vt-tom** [krbz999/class-pages#13]
I tried to configure the Tome of Heroes (Kobold Press) compendium with the module, but now i get an error wenn hitting the wand button:
![grafik](https://github.com/krbz999/class-pages/assets/80099175/26cc0437-947e-44ec-8ebb-1c8f5dc65945)

**Comment by krbz999** [comment]
Does this compendium contain documents that don't have a `system` property, somehow?

**Comment by vt-tom** [comment]
```js
{
			"label": "ToH - Class Options",
			"type": "Item",
			"name": "toh-class-options",
			"path": "./packs/toh-class-options.db"
		},```
yes you are right. The module doesnt contain a system tag by the compediums.

Hmm, this is a bought module. I can change this on my local machine, but if its gets an update, my changes are gone.

**Comment by krbz999** [comment]
No, that part should be fine. I mean specifically the items contained within the compendium.

**Comment by vt-tom** [comment]
Hmm, sorry i dont know how i can check this?
I never opened the `game.packs` section. How can i look into this?

**Comment by krbz999** [comment]
Can you step into the server? I'd like to poke at where this issue is and who caused it. 
https://discord.gg/QAG8eWABGT
