### ISSUE TITLE
Journal Entry Pages Links are broken in Class Pages.

### ISSUE THREAD

**Issue by MythicalRollers** [krbz999/class-pages#14]
Foundry: 11.308
D&D5E: 2.3.1
Class Pages: 11.0.9

I noticed that some links to other compendium journals are broken within CP not the class itself.  Image below. Left is CP with the table link broken, right is the class from the compendium with the link not broken.  I even added test text to see if I was linking the wrong compendium.  The links are valid, and I use them from the Class outside of CP.  To add more to this weirdness, other Compendium journal links are NOT broken, only "some" of them are.  When doing some digging it seems to be related to Journal Entries VS Journal Entry Pages
@UUID[Compendium.mythical-rollers-compendium.mythical-journal-entries.JournalEntry.maEEE3y69tja8TFk]{Spell Rules} (Works)
@UUID[Compendium.mythical-rollers-compendium.mythical-journal-entries.JournalEntry.Yn1CKTMnIfG3fypx.JournalEntryPage.9F6kskJR1RAo2sph]{Spells List} (Does Not Work)
![image](https://github.com/krbz999/class-pages/assets/106455111/96bf01f0-9e61-4530-896c-4ca3edf98626)

**Comment by krbz999** [comment]
Haha, oops, `enrichHTML` is still default `sync`. One-line fix!

**Comment by krbz999** [comment]
Reverting this change due to increase in load times. Blocked by #16.
