### ISSUE TITLE
Enriching html asynchronously significantly increases load time of the pages

### ISSUE THREAD

**Issue by MythicalRollers** [krbz999/class-pages#16]
Using the wand or the macro I created, neither open CP .  No errors in the console.

**Comment by krbz999** [comment]
11.0.10 contained 3 lines of changes, two of them being css. What was your previous version?

**Comment by MythicalRollers** [comment]
Disregard, it just took a very very very long time.
Previous was 11.0.9

**Comment by krbz999** [comment]
> Disregard, it just took a very very very long time. Previous was 11.0.9

Is this reproducible?

**Comment by krbz999** [comment]
Makes sense and is likely due to the enriching of class/subclass descriptions with many content links. I suspect journal *page* links double-dip here.
