### ISSUE TITLE
Load time increased significantly with build 11.0.10

### ISSUE THREAD

**Issue by maxobremer** [krbz999/class-pages#17]
Maybe a weird one, but on the latest build it takes very long to render the class page window, where in the build before it, it renders quite fast.

tested on both the world I run a game in and a near empty one (had this module and a module that was just compendiums with lots of stuff in it (classes, spells, items, etc))
Build [11.0.9](https://github.com/krbz999/class-pages/releases/tag/v11.0.9) loads in a second
Build [11.0.10](https://github.com/krbz999/class-pages/releases/tag/v11.0.10) takes more then a minute, if not a few to load.

**Comment by maxobremer** [comment]
No errors btw, just increased load times

**Comment by krbz999** [comment]
Can you confirm whether you have classes and subclasses with quite a lot of content links in their descriptions

**Comment by maxobremer** [comment]
just now saw this was already mentioned basically in this closed issue, so will close it for now as it was already there

https://github.com/krbz999/class-pages/issues/16
