### ISSUE TITLE
Conflict with Shared Data-style module

### ISSUE THREAD

**Issue by ctbritt** [krbz999/class-pages#18]
Using a shared (non-world) set of compendia, Class Pages chokes and won't open any pages or allow any settings changes. Forces the deactivation of Shared Data module to be useable. 

Errors
<img width="833" alt="image" src="https://github.com/krbz999/class-pages/assets/4516034/6ac00ccd-818e-4ffc-ba60-129379b0831a">

**Comment by krbz999** [comment]
Looking into this, the offending line seems to indicate a bad import of some kind? Have you somehow created an item that not only does not have a description, but doesn't even have the `description` *property?*

Please try v11.0.11.
