### ISSUE TITLE
The New Update is God Awful

### ISSUE THREAD

**Issue by ItsDrafty** [krbz999/class-pages#27]
I don't know who thought replacing the class names with a million icons with no indication of what they are, was a good idea. Why would I want all the subclasses across the banner, that are textless icons mind you, when I could just go to the class page, and subclass section. These new updates actively makes things worse. I now have to skip through a million icons like I'm browsing Netflix until I happen to find the class I want.

**Comment by MaxPat931** [comment]
The way that you express your opinion in this issue indicates that you have no idea of how to work with people collaboratively, and you have no respect for the effort that goes into developing this module.
I have absolutely no relationship with the maintainer of this freely distributed code, but you may want to reconsider your approach and phrase your request in a productive manner.

**Comment by krbz999** [comment]
I wonder if this chucklefuck noticed that the icons _(which use the class items' icons)_ have tooltips and the app renders initially on the primary class of your assigned actor, but I won't be holding my breath for an intelligent response.

Hateclosed, and - with love - you may grab a spoon.
