### ISSUE TITLE
Add alternative to `:has` selector due to firefox

### ISSUE THREAD

**Issue by Sephalopod** [krbz999/class-pages#28]
Hello! I appreciate your work on this mod a lot, and I was very excited for this new toggle. I have 16 third party classes in my compendium, so the spell config window cuts off the last 5 classes in the list. Clicking the "Spellcasting?" toggle doesn't seem to hide any classes, tho. I disabled all other modules, and double-checked all the non-spellcasting classes have spell progression set to None. Currently using Foundry v11 build 309, DnD5e v2.3.1, and Class Pages v11.1.3

**Comment by krbz999** [comment]
What browser?

**Comment by Sephalopod** [comment]
Firefox 119.0

**Comment by krbz999** [comment]
Makes sense. The css `:has` selector is not yet part of Firefox. I'll see what can be done but I'm going to recommend using a different browser for foundry in the meantime. Edge is highly recommended for this.

**Comment by Sephalopod** [comment]
Okay! I'll try it out on Edge. Thanks for looking into it!

**Comment by krbz999** [comment]
FireFox supports `:has` by default since December, so this should no longer be an issue.

https://caniuse.com/?search=%3Ahas
