### ISSUE TITLE
`Gallery` images are stretched

### ISSUE THREAD

**Issue by InnilToo** [krbz999/class-pages#30]
Foundry VTT version 11 Build 315
System DnD 5e version 3.0.2
Class Pages version 11.1.5
Browser: Safari version 17.3.1

I tried to reproduce it in the native app on macOS version 14.3.1, it looks okay there.
It looks okay on Edge version 122.0.2365.63.
Safari was a mistake.

<img width="1680" alt="image" src="https://github.com/krbz999/class-pages/assets/33260912/5c2e7891-975b-4535-a5e2-94979e80c5e4">
<img width="1680" alt="image" src="https://github.com/krbz999/class-pages/assets/33260912/902fade8-40a1-46ec-930d-b0e68b5b351a">

**Comment by krbz999** [comment]
> Safari was a mistake.

Nailed it in one.
