### ISSUE TITLE
Not showing icon

### ISSUE THREAD

**Issue by TheAlbinoRyano** [krbz999/class-pages#32]
I downloaded Class Pages two days ago and couldn't find the icon. I've even deactivated all my modules, and I still can't find the "wand" icon on the left-hand side. Is there a picture of where the icon should be? I have the latest updates on FVTT and for D&D5e

**Comment by krbz999** [comment]
Here, while on the Token layer.

![image](https://github.com/krbz999/class-pages/assets/50169243/2803cf3b-0e76-47cb-9ea2-14132e706e40)

**Comment by TheAlbinoRyano** [comment]
Thanks! Now I feel so dumb because I thought that button had always been there! Now I can finally get everything organized right. I've been looking for a module like this because I have some people not wanting to use the D&D Beyond integrator anymore.
